### ISSUE TITLE
[Meta] AIP11

### ISSUE THREAD

**Issue by supaiku0** [ArkEcosystem/core#2535]
This is a meta issue to track what still needs to be done before we can enable AIP11 for 2.6:

(This list could be incomplete and is subject to change):
- [X] ~~Finish Multi Signature Registration #1590~~
- [X] ~~Finish IPFS #1591~~
- [X] ~~Finish HTLC #2773~~
- [x] ~~Finish Multi Payment #1593~~
- [X] ~~Finish Delegate Resignation #1594~~
- [X] ~~Add fallback for ECDSA signatures (e.g. by checking if length > 64) #2584~~
- [X] ~~Add nonce to wallet transformer #2760~~
- [X] ~~Decide how to extend the type field for custom transaction types~~
- [X] ~~Make transaction asset queryable via API #2618~~
- [X] Resolve remaining tasks related to nonces #2086
- [X] Update Java SDK
