### ISSUE TITLE
4.0 Tracking Issue

### ISSUE THREAD

**Issue by faustbrian** [ArkEcosystem/core#4515]
This is a tracking issue for 4.0 release. Tasks should be worked on from top to bottom.

- [ ] https://github.com/ArkEcosystem/core/issues/4510
- [ ] https://github.com/ArkEcosystem/core/issues/4513
- [ ] https://github.com/ArkEcosystem/core/issues/4511
- [ ] https://github.com/ArkEcosystem/core/issues/4512
- [ ] https://github.com/ArkEcosystem/core/issues/4514
