### ISSUE TITLE
startup script checklist

### ISSUE THREAD

**Issue by fix** [ArkEcosystem/core#611]
I am logging here all what is missing to bootstrap a default node to devnet from scratch. Might be wise to have some decent default so installing (bin/install.sh) and start (last item) is enough (with no configuration)

-  [ ] install npm
-  [ ] install forever
-  [ ] install redis
-  [ ] git clone
-  [ ] enable api plugin in config (not default)
-  [ ] configure ARK_P2P_HOST to the ip to be reachable from outside (maybe default should be null instead of localhost)
-  [ ] configure ARK_API_HOST to the ip to be reachable from outside (maybe default should be null instead of localhost)
-  [ ] start using `forever start ./bin/ark relay --config ./lib/config/devnet --network devnet`

will update issue as soon as i have more
